# docker version
version: '3.7'

# docker service
services:


  # php server
  php:
    build: .
    container_name: php
    restart: always
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80
