# docker version
version: '3.7'

# docker service
services:


  # service database mysqli
  db:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: webapp
    ports:
      - 6033:3306


  # service database management
  adminer:
    image: adminer
    ports:
      - 8080:8080
