# docker version
version: '3.7'

# docker service
services:


  # service php and apache
  php:
    build: docker/php
    container_name: php73
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80
